apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: phaij8420-python 
  janus-idp.io/tekton: phaij8420-python
  backstage.io/kubernetes-id: phaij8420-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: phaij8420-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml