apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: phaij8420-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: phaij8420-python 
  name: phaij8420-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: phaij8420-python 
